### ISSUE TITLE
Trying to install node-red-node-serialport fails

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#1]
Please find the log when I try to install `node-red-node-serialport` using the menu **Manage palette**.

> -----------------------------------------------------------
> 2019-05-24T07:33:48.514Z Install : node-red-node-serialport 0.8.1
> 
> 2019-05-24T07:33:48.517Z /Users/<USER>/Desktop/Node-RED-Desktop.app/Contents/Resources/app.asar/node_modules/npm/bin/npm-cli.js install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-serialport@0.8.1
> 2019-05-24T07:33:50.029Z [err] npm WARN
> 2019-05-24T07:33:50.029Z [err]  lifecycle npm is using /Users/<USER>/Desktop/Node-RED-Desktop.app/Contents/Frameworks/Node-RED-Desktop Helper.app/Contents/MacOS/Node-RED-Desktop Helper but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 2019-05-24T07:33:50.029Z [out] 
> 2019-05-24T07:33:50.029Z [out] > @serialport/bindings@2.0.8 install /Users/<USER>/.Node-RED-Desktop/node_modules/@serialport/bindings
> 2019-05-24T07:33:50.029Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
> 2019-05-24T07:33:50.029Z [out] 
> 2019-05-24T07:33:50.036Z [err] env: node: No such file or directory
> 2019-05-24T07:33:50.037Z [err] sh: node-gyp: command not found
> 2019-05-24T07:33:50.186Z [err] npm ERR! file sh
> 2019-05-24T07:33:50.187Z [err] npm ERR! code ELIFECYCLE
> 2019-05-24T07:33:50.187Z [err] npm ERR! errno ENOENT
> 2019-05-24T07:33:50.187Z [err] npm ERR! syscall spawn
> 2019-05-24T07:33:50.187Z [err] npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
> 2019-05-24T07:33:50.187Z [err] npm ERR! spawn ENOENT
> 2019-05-24T07:33:50.187Z [err] npm
> 2019-05-24T07:33:50.187Z [err]  ERR! 
> 2019-05-24T07:33:50.187Z [err] npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
> 2019-05-24T07:33:50.187Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 2019-05-24T07:33:50.211Z [err] 
> 2019-05-24T07:33:50.211Z [err] npm 
> 2019-05-24T07:33:50.212Z [err] ERR! A complete log of this run can be found in:
> 2019-05-24T07:33:50.212Z [err] npm ERR!     /Users/<USER>/.npm/_logs/2019-05-24T07_33_50_191Z-debug.log
> 2019-05-24T07:33:50.220Z rc=1

Thank you!

**Comment by sakazuki** [comment]
Hello @rei-vilo 

Thank you for your report.
Some  npm modules need to be compiled from node binary or C/C++ when installing.

When you install those modules, you need to install node.js before.
Please install node v12.x.x  from https://nodejs.org/

Then retry to install node-red-node-serialport.

Regards,

sakazuki

**Comment by rei-vilo** [comment]
Thank you for your prompt answer.

I updated nodes from `v10.15.3`to `v12.3.1`.

However, the same issue is raised.

> -----------------------------------------------------------
> 2019-05-24T14:26:16.819Z Install : node-red-node-serialport 0.8.1
> 
> 2019-05-24T14:26:16.832Z /Applications/IDE/Node-RED-Desktop.app/Contents/Resources/app.asar/node_modules/npm/bin/npm-cli.js install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-serialport@0.8.1
> 2019-05-24T14:26:24.226Z [err] npm WARN lifecycle npm is using /Applications/IDE/Node-RED-Desktop.app/Contents/Frameworks/Node-RED-Desktop Helper.app/Contents/MacOS/Node-RED-Desktop Helper but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 2019-05-24T14:26:24.227Z [out] 
> 2019-05-24T14:26:24.227Z [out] > @serialport/bindings@2.0.8 install /Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings
> 2019-05-24T14:26:24.227Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
> 2019-05-24T14:26:24.227Z [out] 
> 2019-05-24T14:26:24.236Z [err] env: node: No such file or directory
> 2019-05-24T14:26:24.236Z [err] sh: node-gyp: command not found
> 2019-05-24T14:26:24.468Z [err] npm ERR! file sh
> 2019-05-24T14:26:24.469Z [err] npm ERR! code ELIFECYCLE
> 2019-05-24T14:26:24.469Z [err] npm ERR! errno ENOENT
> 2019-05-24T14:26:24.469Z [err] npm ERR! syscall spawn
> 2019-05-24T14:26:24.469Z [err] npm ERR!
> 2019-05-24T14:26:24.469Z [err]  @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
> 2019-05-24T14:26:24.469Z [err] npm ERR! spawn ENOENT
> 2019-05-24T14:26:24.469Z [err] npm ERR! 
> 2019-05-24T14:26:24.469Z [err] npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
> 2019-05-24T14:26:24.469Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 2019-05-24T14:26:24.517Z [err] 
> 2019-05-24T14:26:24.517Z [err] npm ERR! A complete log of this run can be found in:
> 2019-05-24T14:26:24.517Z [err] npm ERR!     /Users/USER/.npm/_logs/2019-05-24T14_26_24_472Z-debug.log
> 2019-05-24T14:26:24.526Z rc=1

I'm attaching the mentionned `2019-05-24T14_26_24_472Z-debug.log` file, as it may contains hints of the cause.

[2019-05-24T14_26_24_472Z-debug.log](https://github.com/sakazuki/node-red-desktop/files/3217377/2019-05-24T14_26_24_472Z-debug.log)

However, if I use Node-RED from the command line (not with your nice desktop app), asking for `node-red-node-serialport` to be installed succeeds.

**Comment by sakazuki** [comment]
I saw your log.
It looks Node-RED-Desktop does not have PATH environment variable to `/usr/local/bin`.
Maybe you execute `node -v`  in an exec node on Node-RED-Desktop, it will fail.

Try to launch Node-RED-Desktop from shell with `open /Applications/Node-RED-Desktop.app`.
Then check whether `node -v` execution run success. If success, try to install `node-red-node-serialport`.

You will be able to install `node-red-node-serialport`.
But it is not enough. It will occur the following error.

```
[2019-05-25 09:44:03.861] [info]  - node-red-node-serialport:serial in : Error: The module '/Users/sakazuki/.Node-RED-Desktop/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```

You need some steps to fix it.

```
$ npm install -g electron-rebuild
$ cd $USER/.Node-RED-Desktop
$ electron-rebuild --version 5.0.0
✔ Rebuild Complete
$ open /Applications/Node-RED-Desktop.app
```
Then it will work.

Regards,

P.S.
- I usually use Windows. And I am not familiar with Mac.
So I want to know the way to configure the environment variables when launching Node-RED-Desktop from Launchpad
- I will improve this steps more simple in the future version.

**Comment by rei-vilo** [comment]
Thank you so much for the detailed instructions. 

Installing `node-red-node-serialport` for Node-RED-Desktop succeeded.
