### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#10]
Please find a couple of issues.

* Download error message

When I launch Node-RED-Desktop `0.9.1`, I'm prompted to download the new release `0.9.2`. 

<img width="420" alt="Capture  2019-07-13 à 20 18 32" src="https://user-images.githubusercontent.com/951776/61175269-84a6e980-a5ac-11e9-8409-73388de01d0a.png">

However, download fails with the following message:

<img width="396" alt="Capture  2019-07-13 à 14 45 57" src="https://user-images.githubusercontent.com/951776/61175206-98058500-a5ab-11e9-88af-b603c9c34a37.png">

* Node-RED-Desktop `0.9.2` goes back to `0.9.1`!

So I've downloaded and installed release `0.9.2` manually.

<img width="420" alt="Capture  2019-07-13 à 20 19 24" src="https://user-images.githubusercontent.com/951776/61175242-15c99080-a5ac-11e9-8a1f-b9149c54d661.png">

However, after a couple of launches, Node-RED-Desktop returns to release `0.9.1`!

<img width="420" alt="Capture  2019-07-13 à 20 23 06" src="https://user-images.githubusercontent.com/951776/61175243-1b26db00-a5ac-11e9-9572-a925b8c4b62c.png">

What is going on? Thank you!

**Comment by sakazuki** [comment]
Hi
I can confirmed the download error message
 `Could not get code signature for running application`.

But I cannot confirmed the `Node-RED-Desktop 0.9.2 goes back to 0.9.1!`.
Because there is no code to downgrade version in Node-RED-Desktop, 
I think it maybe was launched from other binary ?

**Comment by rei-vilo** [comment]
Thank you for your prompt answer. 

I performed a fresh install of Node-RED-Desktop, _i.e._ deleting the previous release and installing from scratch, to no avail.

I'm sorry I forgot to mention I'm using macOS.
