### ISSUE TITLE
Idea: Add context data storage

### ISSUE THREAD

**Issue by SuperNinja73** [sakazuki/node-red-desktop#11]
Hi Sakazuki, thanks for your work ,
It would be nice to add support for persistent variables. At each update of NRD I lose all my measurements. Maybe, are you already working on it? ;)

**Comment by sakazuki** [comment]
Hi,

I released v0.9.4 including this.
Please try it.

Usage: 
https://github.com/sakazuki/node-red-desktop/wiki#how-to-use-context-storage
