### ISSUE TITLE
Question: bind Node-Red-Desktop on fix local port

### ISSUE THREAD

**Issue by ronopitz** [sakazuki/node-red-desktop#13]
Hi,

is there a solution to bind Node-Red-Desktop to a fix local port?
After every start Node-Red-Desktop is arrival over a different port.
Ngrok is not a solution, I don't need access from the Internet. Only local networks or local computer.

Thank Ron

**Comment by sakazuki** [comment]
Hi,

You can fix the listen port with **NRD_LISTEN_PORT** environment variable.

See also [wiki page](https://github.com/sakazuki/node-red-desktop/wiki#environment-variables)

Regards,
sakazuki
