### ISSUE TITLE
macOS no longer supported?

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#14]
The last releases `0.9.5-beta` and `0.9.5-beta-2` only provide binaries for Windows.

Is macOS still supported?

Thank you!

**Comment by sakazuki** [comment]
macOS is still supported.
I will support also macOS version in release version.
In pre-release phase, I have not enough time to test for macOS

Regards,

**Comment by rei-vilo** [comment]
Good to know, thank you!
