### ISSUE TITLE
Node-RED-Desktop refuses to launch on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#15]
Node-RED-Desktop refuses to launch on macOS 10.15 _Catalina_.

<img width="420" alt="Capture d’écran 2019-10-13 à 20 10 41" src="https://user-images.githubusercontent.com/951776/66719872-a60ab200-edf5-11e9-8d2b-6f83a84b92f5.png">

**Comment by sakazuki** [comment]
I released v1.0.0-beta.1.
Please try it.

**Comment by rei-vilo** [comment]
Thank you! I'll give a try.

**Comment by rei-vilo** [comment]
Unfortunately, release v1.0.0-beta.1. refuses to launch on macOS 10.15 _Catalina_.

<img width="420" alt="66719872-a60ab200-edf5-11e9-8d2b-6f83a84b92f5" src="https://user-images.githubusercontent.com/951776/68082105-ba503680-fe18-11e9-85fa-3c2ce1668067.png">

**Comment by sakazuki** [comment]
I could confirm the same error. Those zip files are corrupted.
I hide .zip files in releases page 1.0.0-beta.1, 2 .

Regards

**Comment by sakazuki** [comment]
I could confirmed the error with .zip file.
Those .zip files maybe are corrupted.
So  I deleted  1.0.0-beat.1,2 .zip files in release page .

Regards

**Comment by sakazuki** [comment]
I built a mac binary on Catalina 10.15.1 and I can launch it correctly.
I want to know  the steps to reproduce the error.

**Comment by sakazuki** [comment]
I confirmed the error with zip file.
Maybe those zip files are corrupted.
I delete 1.0.0-beta.1,2 's zip files

Regards,

**Comment by rei-vilo** [comment]
The `.zip` distribution fails while the `.dmg` succeeds.

- Download Node-RED-Desktop-1.0.0-beta.1-mac.zip
- Unzip it and place Node-RED-Desktop under /Applications
- Double-click on Node-RED-Desktop
- Node-RED-Desktop fails to launch and prompts the error message.

but

- Download Node-RED-Desktop-1.0.0-beta.1.dmg
- Open it and place Node-RED-Desktop under /Applications
- Double-click on Node-RED-Desktop
- Node-RED-Desktop launches successfully

**Comment by rei-vilo** [comment]
Thanks!
