### ISSUE TITLE
Listen Port needs checking

### ISSUE THREAD

**Issue by cymplecy** [sakazuki/node-red-desktop#17]
Hi sakazuki :)
I made a mistake and typed in 181880 instead of 11880 when I tried it and the application just sits looking like this - I think it needs some checking on the value if possible
![image](https://user-images.githubusercontent.com/2357428/69913517-96d8d580-1430-11ea-8558-3631890687da.png)

**Comment by sakazuki** [comment]
Thank you for your report.
I will add the validation of port number.

**Comment by sakazuki** [comment]
done  in v1.1.0
