### ISSUE TITLE
Some nodes missing from standard Node-RED package 

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#2]
I'm comparing the command-line Node-RED (left) with the Node-RED-Desktop (right).

Some nodes are missing from the Node-RED-Desktop.

* For **inputs**: MQTT, UDP, UDP

<img width="423" alt="Capture  2019-05-25 à 09 21 35" src="https://user-images.githubusercontent.com/951776/58366209-2aa07680-7ecf-11e9-8762-12b599d855c3.png">

* For **outputs**: MQTT, UDP, UDP

<img width="433" alt="Capture  2019-05-25 à 09 21 43" src="https://user-images.githubusercontent.com/951776/58366210-2b390d00-7ecf-11e9-86ab-23453868b7a3.png">

All those nodes are part of the standard `node-red` package.

* Is there a technical reason for the Node-RED-Desktop to not feature them? I'd be especially interested in the MQTT nodes.

* How to activate them?

**Comment by sakazuki** [comment]
Hello @rei-vilo 

You can activate them at [Nodes exclude] form in [File]-[Settings...].
When you activate the MQTT node, Delete `10-mqtt.js` from [Node exclude].

I have selected default [Nodes exclude] to simple the first look for beginners.
There is not technical reason.

Regards,
sakazuki

**Comment by rei-vilo** [comment]
Thank you for the explanations. The MQTT nodes are available now.
