### ISSUE TITLE
How to set the level of verbosity of the **debug** panel?

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#20]
By default, Node-RED-Desktop prints the trace for all nodes on the **debug** panel,

<img width="1440" alt="Capture d’écran 2020-02-22 à 16 35 44" src="https://user-images.githubusercontent.com/951776/75095118-17bbef00-5592-11ea-9d16-3f8e51174cc7.png">

while standard Node-RED only reports the output of the debug node.

<img width="1278" alt="Capture d’écran 2020-02-22 à 16 37 19" src="https://user-images.githubusercontent.com/951776/75095134-3d48f880-5592-11ea-9be8-a97d7e23f3eb.png">

How to set the level of verbosity of the **debug** panel for Node-RED-Desktop?

Thank you!

**Comment by sakazuki** [comment]
Unfortunately, there is no way to set the level of verbosity of it.

**Comment by rei-vilo** [comment]
Can it be switched off?

**Comment by sakazuki** [comment]
Toggle off in **[Extend]-[Debug out]**

**Comment by rei-vilo** [comment]
Thanks!
