### ISSUE TITLE
cannot config setting.js

### ISSUE THREAD

**Issue by d0uub** [sakazuki/node-red-desktop#23]
i want to load an external npm node and it already done in "add a remote node" but it cannot load `require` even i have following configuration at `%USERPROFILE%\.Node-RED-Desktop\settings.js`
```
module.exports = {
  functionGlobalContext: {
    require:require
  }
}
```
or can make it default or able to config at "Settings..."? thanks.

**Comment by sakazuki** [comment]
Currently, User settings are merged in shallow with Node-RED-Desktop default settings.
- Node-RED-Desktop default settings is defined in the code https://github.com/sakazuki/node-red-desktop/blob/febb28c81a5903a23e41eff31b3218ccfc9434e4/src/main/node-red.ts#L88-L164
- User's functionGlobalContext is overwritten with the default's one

I will plan to update the specification of user settings ( maybe I will use deep merge...) in next release.

**Comment by d0uub** [comment]
thank you!

**Comment by sakazuki** [comment]
done  in v1.1.0
