### ISSUE TITLE
Idea: Dashboard on the Same App

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#3]
This is just an idea, to be discussed.. 

Instead of launching a separate browser for the dashboard, could the IDE and the Dashboard be under the same app?

**Comment by sakazuki** [comment]
Hi @rei-vilo ,

Thank you for your idea.

I understand "the Dashboard" means this (https://flows.nodered.org/node/node-red-dashboard).

I am not familiar with the dashboard. 
Could you let me know the idea more detail,  now I don't know the good point to used it in the same app.

My thought is that the editor is for flow creators, but the dashboard is for users.

Regards,
sakazuki

**Comment by rei-vilo** [comment]
Hi @sakazuki,

Thank you for the prompt answer.

One of the key features of Node-RED is the dashboard, which provides all the GUI elements for a command-and-control panel.

When used in command-line mode, Node-RED provides two addresses:

+ http://127.0.0.1:1880 for the IDE, and
+ http://127.0.0.1:1880/ui for the dashboard.

For example, the following dashboard...

<img width="330" alt="Capture  2019-05-26 à 23 13 45" src="https://user-images.githubusercontent.com/951776/58387241-13b36e80-800c-11e9-8ae9-deaf48ed0621.png">

...has the corresponding code

> [{"id":"e29f40ae.dc2ed","type":"ui_gauge","z":"7ce61b5f.bdd744","name":"","group":"c15d2070.9f5a4","order":1,"width":0,"height":0,"gtype":"gage","title":"gauge","label":"units","format":"{{value}}","min":0,"max":10,"colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":440,"y":180,"wires":[]},{"id":"6f03ce05.75a94","type":"ui_slider","z":"7ce61b5f.bdd744","name":"","label":"slider","tooltip":"","group":"c15d2070.9f5a4","order":0,"width":0,"height":0,"passthru":true,"outs":"all","topic":"","min":0,"max":10,"step":1,"x":220,"y":120,"wires":[["e29f40ae.dc2ed"]]},{"id":"c15d2070.9f5a4","type":"ui_group","z":"","name":"Default","tab":"9e7f0f63.821678","disp":true,"width":"6","collapse":false},{"id":"9e7f0f63.821678","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]

Today, Node-RED Desktop exposes the IDE window, but not the dashboard window. This means I need an external browser to display the dashboard.

The idea would be Node-RED Desktop provides both windows, saving the need for a browser.

Summarising the options, 

+ The command-line mode requires two applications: 
    1. a terminal to launch `node-red`; 
    2. a browser with two windows: one for IDE at http://127.0.0.1:1880, and another for the dashboard at http://127.0.0.1:1880/ui.

+ Using Node-RED Desktop still requires two applications: 
    1. Node-RED Desktop for launching Node-RED and for displaying the IDE; 
    2. A browser for the dashboard at 127.0.0.1:1880/ui

+ Suggested Node-RED Desktop implementation with one single application:
    1. Node-RED Desktop for launching Node-RED, displaying the IDE and the dashboard.

**Comment by rei-vilo** [comment]
You may pay a visit at a similar project, **electron-node-red** at https://github.com/zuhito/electron-node-red.

The Electron unique window shows the editor and the dashboard, among other options, although not in different tabs.

**Comment by sakazuki** [comment]
In v1.0.0-beta.5,
I add a new function to open in the same app by clicking a link with Ctrl (mac: Command)

**Comment by rei-vilo** [comment]
Very nice!

<img width="317" alt="Capture d’écran 2019-11-11 à 09 07 53" src="https://user-images.githubusercontent.com/951776/68571332-0b88a780-0463-11ea-88fc-729d7651db8e.png">

**Comment by sakazuki** [comment]
done
