### ISSUE TITLE
change file locations?

### ISSUE THREAD

**Issue by tribbles3** [sakazuki/node-red-desktop#31]
I see that you can set the user directory but is there a way to change the other two locations (in windows)?

executable location: C:\Users\xxxxx\AppData\Local\Programs\node-red-desktop\

caches, strorage, etc.: C:\Users\xxxxx\AppData\Roaming\Node-RED-Desktop\

I am attempting to make this as portable as possible. Thanks.

**Comment by sakazuki** [comment]
Unfortunately there is no way to change the other locations.
These locations are depend on the [Electron internal rule](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname).

**Comment by tribbles3** [comment]
Ok, thanks for the reply and link.
