### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by mataherry** [sakazuki/node-red-desktop#34]
I don't know if it's been asked before, how do you run multiple instances of node-red-desktop? I tried using 2 separate folders with 2 user directories, but they seem to launch using the same default settings. Thank you.

**Comment by sakazuki** [comment]
Hi @mataherry,

Sorry for late comment.
When you set [File]-[Settings]-[Node-RED]-[Listen port] with blank, then you can launch multiple Node-RED-Desktops.

**Comment by mataherry** [comment]
Hi @sakazuki your suggestions works, I was able to launch multiple Node-RED-Desktops, but is there any way to load different settings.js or userDir from the command line? Thank you.

**Comment by sakazuki** [comment]
@mataherry 
> is there any way to load different settings.js or userDir from the command line?
There is no way to do it.

**Comment by mataherry** [comment]
Ok thank you @sakazuki for your awesome work!
