### ISSUE TITLE
Open local/public URL not working

### ISSUE THREAD

**Issue by zeldalegends** [sakazuki/node-red-desktop#36]
Hi sakazuki,

thanks for your great work! I am usinf v1.2.2 and I noticed that both "Open a local URL" and "Open a pulic URL" (when connecting ngrok) are not working, sinche the browser replies with "Cannot GET /" in both cases.

Hope this may help.
Thanks in advance.
Best regards.

**Comment by mataherry** [comment]
To open the editor you need to add /admin 
e.g: http://127.0.0.1:54882/admin

**Comment by zeldalegends** [comment]
Many thanks. I have tried this workaround also for "Open a public URL", trying to append "/admin" to the ngrok endpoint (https://***********.ngrok.io/admin), but it responds with: {"error":"Access denied to IP address: ***.***.***.***"}. Is there a chance to see the editor through the public URL?

**Comment by mataherry** [comment]
From https://sakazuki.github.io/node-red-desktop/ 
How to publish the HTTP endpoint
1. create a flow using “http in” and “http response” nodes and deploy it.
2. click [Endpoint]-[Connect ngrok]
3. you will get the domain such as https://1234xxxx.ngrok.com.
4. access to the above public url.

I might be mistaken, but I think for ngrok it only forwards the http in and http response nodes
e.g: https://43b1b9c53569.ngrok.io/test

**Comment by sakazuki** [comment]
@zeldalegends 

> Is there a chance to see the editor through the public URL?

When you use the environment variable **NRD_IP_ALLOWS**, then you can access the admin page with the public url from the source ip addresses of **NRD_IP_ALLOWS**.

see: https://github.com/sakazuki/node-red-desktop/wiki#environment-variables

**Comment by sakazuki** [comment]
I closed this issue because of  non update
