### ISSUE TITLE
macOS: Window top bar doesn't allow to move the window

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#4]
When clicking on the top of the Node-RED Desktop window to move it, the text `Node-RED Desktop ... Deploy` is selected but the window doesn't move. 

<img width="1243" alt="Capture  2019-05-26 à 23 33 30" src="https://user-images.githubusercontent.com/951776/58387465-c97fbc80-800e-11e9-816b-90c72473a4be.png">

**Comment by sakazuki** [comment]
Hi @rei-vilo,

Thank you for your report.
I confirmed it. 

And I have already fixed it, and I will include this fix in next release.

Regards,
sakazuki

**Comment by rei-vilo** [comment]
Thanks!

**Comment by rei-vilo** [comment]
The bug is back with release 1.0.0-beta-1.

<img width="420" alt="Capture d’écran 2019-11-04 à 10 23 34" src="https://user-images.githubusercontent.com/951776/68111454-71b77c80-feef-11e9-91c9-366494cea3d2.png">

<img width="1280" alt="Capture d’écran 2019-11-04 à 10 38 54" src="https://user-images.githubusercontent.com/951776/68111468-7aa84e00-feef-11e9-8b26-4371371c1ffe.png">

**Comment by sakazuki** [comment]
Thank you for your report.
This is an effect of the node-red updates.
I will fix it.

**Comment by sakazuki** [comment]
I fixed this in v1.0.0-beta.5
