### ISSUE TITLE
 ngrok's Authtoken

### ISSUE THREAD

**Issue by kent1026** [sakazuki/node-red-desktop#45]
Is possible to use ngrok's Authtoken?
is useful to demo web app and classroom.
thanks.

**Comment by sakazuki** [comment]
Yes, you can.
Put a file at ~/.ngrok2/ngrok.yml.
```
# in ngrok.yml
authtoken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by Nikhil9938** [comment]
![IMG_20210605_085103.jpg](https://user-images.githubusercontent.com/84974395/120878618-4f11ac00-c5db-11eb-8ff1-06c89f44c4dd.jpg) i need help
Its shows bash: bad address ./ngrok

**Comment by sakazuki** [comment]
@Nikhil9938 
Use **%USERPROFILE%\AppData\Local\Programs\Node-RED-Desktop\resources\app.asar.unpacked\node_modules\ngrok\bin\ngrok.exe**  on Command Prompt (Windows application).

**Comment by Nikhil9938** [comment]
> @Nikhil9938 
> Use **%USERPROFILE%\AppData\Local\Programs\Node-RED-Desktop\resources\app.asar.unpacked\node_modules\ngrok\bin\ngrok.exe**  on Command Prompt (Windows application).
> 

for android pls

**Comment by sakazuki** [comment]
> for android pls
Unfortunately it is not possible because of Node-RED-Desktop depends on [Electron](https://www.electronjs.org/).
