### ISSUE TITLE
Please also make similar app for n8n.io

### ISSUE THREAD

**Issue by ch3ckmat3** [sakazuki/node-red-desktop#52]
Node-Red desktop is great app for quickly prototyping ideas and testing logic and APIs.

Please also look at https://n8n.io/ which offer many connectors to popular services out-of-the-box and can be used with Node-Red to consume these services. 

It will be great to have a similar desktop version of n8n.io.

**Comment by gasolin** [comment]
@ch3ckmat3 here it is https://docs.n8n.io/getting-started/installation/#desktop-app

**Comment by ch3ckmat3** [comment]
Oh great! Thank you for the pointer.
