### ISSUE TITLE
the menu bar disappeared after the 2.1.0 update

### ISSUE THREAD

**Issue by SuperNinja73** [sakazuki/node-red-desktop#57]
![image](https://user-images.githubusercontent.com/53425740/139866113-e943c9a6-e358-4cfe-8784-0a55a1c44df3.png)
problem or not? How to make it reappear?

**Comment by sharonv** [comment]
When I saw the issue initially I remembered that some windows apps have this as built in, you can press ALT key and it will appear. it's not a bad idea to keep it as an option IMHO

**Comment by SuperNinja73** [comment]
@sharonv yes , ALT working Thanks .  When we got used to it, it's hard to do without. I would try to remember it.

**Comment by SuperNinja73** [comment]
Display by pressing the ALT key (win10). Maybe put it back by default?
