### ISSUE TITLE
macOS: Interface Consistency Suggestions

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#6]
Please find some suggestions to improve the consistency of the interface between Node-RED Desktop and other macOS applications.

+ File > Quit would go under Node-RED-Desktop > Quit
+ File > Settings... would go under Node-RED-Desktop > Preferences...
+ Endpoint > ngrok Connect could be renamed Endpoint > Connect ngrok 
+ Endpoint > ngrok Disconnect could be renamed Endpoint > Disconnect ngrok
+ Help > Version could be merged with Node-RED-Desktop > About
+ Help > Check Update... would go under Node-RED-Desktop > Check Update...

**Comment by sakazuki** [comment]
Thank you for your suggestion.
I'm not familiar with Mac, so it's very helpful
I want to use the same code as much as possible for Windows, so I wonder how far I can do it.

Regards,
sakazuki

**Comment by rei-vilo** [comment]
You’re welcome! Those are just suggestions, but Electron seems to handle specific code for the différents platforms quite easily.

**Comment by sakazuki** [comment]
I updated menu interface in v0.9.0-beta.1 almost based on this suggestion.

**Comment by rei-vilo** [comment]
Very nice, thank you!
