### ISSUE TITLE
Really portable

### ISSUE THREAD

**Issue by SebCanet** [sakazuki/node-red-desktop#69]
Hello,
as I was investigating inside your code, after building it, I saw that you mention few directories:
```
Windows

    %USERPROFILE%\.Node-RED-Desktop\
    %USERPROFILE%\AppData\Local\Programs\Node-RED-Desktop\
    %USERPROFILE%\AppData\Roaming\Node-RED-Desktop\
```
But is it possible NOT to use this folders and use only subfolders inside Node-red-desktop installation folder? and make it really portable?
Many thanks.

**Comment by tribbles3** [comment]
I already asked and the answer unfortunately is no.
Original question and answer: https://github.com/sakazuki/node-red-desktop/issues/31

**Comment by SebCanet** [comment]
My mistake...sorry, thanks for answering.

**Comment by SebCanet** [comment]
I think I have an answer, thnks to your documentation link: [https://github.com/electron/electron/blob/main/docs/api/app.md#appgetpathname](https://github.com/electron/electron/blob/main/docs/api/app.md#appgetpathname)

Here's my code:
```
let appgetPathDev = app.getPath('exe');
appgetPathDev = path.dirname(appgetPathDev) 

app.setPath('home', appgetPathDev + '\\temp');
app.setPath('appData', appgetPathDev + '\\temp');
app.setPath('userData', appgetPathDev + '\\temp');
app.setPath('temp', appgetPathDev + '\\temp');
app.setPath('logs', appgetPathDev + '\\temp');
app.setPath('crashDumps', appgetPathDev + '\\temp');
```
Do you think this could help?

**Comment by tribbles3** [comment]
Were you able to get that to work?

**Comment by SebCanet** [comment]
It seems to work, but maybe it needs tests with tracking tool to be sure...

**Comment by tribbles3** [comment]
Did you test copying the folder to another computer to see if it worked properly?

**Comment by SebCanet** [comment]
Tested only on W10x64 + W7x64, and it works. But I tested on my project, on yours I'm not sure where put this information...

**Comment by tribbles3** [comment]
That is exactly what I am using a mix of Win10 & Win7 computers. Where do you run that code to get the paths set?

**Comment by SebCanet** [comment]
In the main.js file, at th top, before  any function definition.
