### ISSUE TITLE
Idea: Add Relaunch option on menu

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#7]
Very often, updating nodes through the **Palette** requires restarting Node-RED.

The **View** menu offers the **Reload** command to refresh the screen.

The idea is to add a command to relaunch the underlying Node-RED service.

**Comment by sakazuki** [comment]
It is a good idea.
I also want it.
I will add this option.

Regards,
sakazuki

**Comment by sakazuki** [comment]
In v0.9.0-beta.2., a relaunch menu was added.

Regards,

**Comment by rei-vilo** [comment]
Great, thanks!
