### ISSUE TITLE
Latest install 2.1.0 : no menus visible

### ISSUE THREAD

**Issue by justoke** [sakazuki/node-red-desktop#70]
I've installed version 2..1.0 by running the setup.exe from the releases section - although it shows version 2.1.2 on in the app menu. I'm using Windows 64bit PC.

The File Endpoint View and Help menus are not visible.  

![image](https://user-images.githubusercontent.com/26506785/161535488-a9b2ab8d-7bcc-49d9-805f-bcd473b09d57.png)

Do I have to install node js before installing using the installer?

**Comment by SuperNinja73** [comment]
Press left "ALT" and the menus are showing

**Comment by justoke** [comment]
Thank you. Probably obvious, but not to me.
