### ISSUE TITLE
Issue — Release 0.9.1 fails to launch due to missing JSON

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#8]
Launching **Node-RED-Desktop** release `0.9.1` raises the following error:

<img width="509" alt="Capture  2019-06-18 à 19 51 44" src="https://user-images.githubusercontent.com/951776/59707400-d6a15d00-9202-11e9-8a09-1b854d046af2.png">

> Error: schema with key or id "http://json-schema.org/draft-06/schema" already exists (line:22)

<img width="578" alt="Capture  2019-06-18 à 19 51 27" src="https://user-images.githubusercontent.com/951776/59707426-e28d1f00-9202-11e9-9c76-99ff8739cc17.png">

The very same flow worked fine with previous version `0.9.0 beta 2`.

When performing a fresh install of **Node-RED-Desktop** release `0.9.1`, the `json` node is missing.

**Comment by sakazuki** [comment]
Thank you for your reports.

This is a build problem on my mac.
I had replaced the mac binary in v0.9.1.

Please download and install the replaced one manually. 

Regards,
sakazuki

**Comment by rei-vilo** [comment]
Everything works fine with the new package. Thank you!
