### ISSUE TITLE
Suggestion: Turn "Checking for update..." notification off

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#9]
By default, when **Check updates on startup** is activated, a notification "Checking for update..." is displayed at launch.

<img width="396" alt="Capture  2019-06-24 à 18 09 26" src="https://user-images.githubusercontent.com/951776/60161240-693f8e80-97f7-11e9-9313-13ffacc0c896.png">

Could this notification be turned off, and be replaced by "Downloading update" in case a new version is available?

**Comment by sakazuki** [comment]
Hi, @rei-vilo 

Sorry for late comment.
Thank you for your suggestion. 

I want to confirm the your suggestion.
What your suggest is,
it is better to hide the notification "Checking for update...."  keeping the flag of **Check updates on startup** is enabled.

Is it correct?
it is noisy or needless ?

**Comment by rei-vilo** [comment]
Yes, it is just hiding the notification when checking for new releases.
